import { ethers } from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  console.log("Starting deployment of OffGridFlow Carbon Credit contracts...\n");

  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Deploy AnchorContract
  console.log("Deploying AnchorContract...");
  const AnchorContract = await ethers.getContractFactory("AnchorContract");
  const anchorContract = await AnchorContract.deploy();
  await anchorContract.waitForDeployment();
  const anchorAddress = await anchorContract.getAddress();
  console.log("✓ AnchorContract deployed to:", anchorAddress, "\n");

  // Deploy CarbonCreditNFT
  console.log("Deploying CarbonCreditNFT...");
  const CarbonCreditNFT = await ethers.getContractFactory("CarbonCreditNFT");
  const carbonCreditNFT = await CarbonCreditNFT.deploy();
  await carbonCreditNFT.waitForDeployment();
  const nftAddress = await carbonCreditNFT.getAddress();
  console.log("✓ CarbonCreditNFT deployed to:", nftAddress, "\n");

  // Deploy CarbonCreditMarketplace
  console.log("Deploying CarbonCreditMarketplace...");
  const CarbonCreditMarketplace = await ethers.getContractFactory("CarbonCreditMarketplace");
  const marketplace = await CarbonCreditMarketplace.deploy(nftAddress);
  await marketplace.waitForDeployment();
  const marketplaceAddress = await marketplace.getAddress();
  console.log("✓ CarbonCreditMarketplace deployed to:", marketplaceAddress, "\n");

  // Grant MINTER_ROLE to marketplace (so it can mint on behalf of users)
  console.log("Configuring permissions...");
  const MINTER_ROLE = await carbonCreditNFT.MINTER_ROLE();
  await carbonCreditNFT.grantRole(MINTER_ROLE, marketplaceAddress);
  console.log("✓ Granted MINTER_ROLE to marketplace\n");

  // Save deployment addresses
  const deploymentInfo = {
    network: (await ethers.provider.getNetwork()).name,
    chainId: Number((await ethers.provider.getNetwork()).chainId),
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    contracts: {
      AnchorContract: anchorAddress,
      CarbonCreditNFT: nftAddress,
      CarbonCreditMarketplace: marketplaceAddress,
    },
  };

  const deploymentPath = path.join(__dirname, "..", "deployments.json");
  const existingDeployments = fs.existsSync(deploymentPath)
    ? JSON.parse(fs.readFileSync(deploymentPath, "utf8"))
    : {};

  existingDeployments[deploymentInfo.chainId] = deploymentInfo;

  fs.writeFileSync(deploymentPath, JSON.stringify(existingDeployments, null, 2));
  console.log("✓ Deployment info saved to deployments.json\n");

  // Generate Go configuration
  const goConfig = `// Code generated by deploy.ts - DO NOT EDIT
// Deployment Date: ${deploymentInfo.timestamp}

package blockchain

const (
	// Ethereum Contract Addresses
	AnchorContractAddress     = "${anchorAddress}"
	CarbonCreditNFTAddress    = "${nftAddress}"
	MarketplaceContractAddress = "${marketplaceAddress}"
)
`;

  fs.writeFileSync(path.join(__dirname, "..", "..", "contracts.go"), goConfig);
  console.log("✓ Generated Go configuration file\n");

  // Print summary
  console.log("=".repeat(70));
  console.log("DEPLOYMENT SUMMARY");
  console.log("=".repeat(70));
  console.log("Network:", deploymentInfo.network);
  console.log("Chain ID:", deploymentInfo.chainId);
  console.log();
  console.log("Contract Addresses:");
  console.log("  - AnchorContract:          ", anchorAddress);
  console.log("  - CarbonCreditNFT:         ", nftAddress);
  console.log("  - CarbonCreditMarketplace: ", marketplaceAddress);
  console.log();
  console.log("Next Steps:");
  console.log("  1. Verify contracts on Etherscan:");
  console.log(`     npx hardhat verify --network ${deploymentInfo.network} ${anchorAddress}`);
  console.log(`     npx hardhat verify --network ${deploymentInfo.network} ${nftAddress}`);
  console.log(`     npx hardhat verify --network ${deploymentInfo.network} ${marketplaceAddress} ${nftAddress}`);
  console.log();
  console.log("  2. Update .env file with contract addresses");
  console.log("  3. Test the deployment with example transactions");
  console.log("=".repeat(70));
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
