package compliance

// report_pdf.go renders an InventoryReport into an audit-ready, assurance-grade
// PDF structured for California SB 253 / the GHG Protocol Corporate Standard.
// Every figure in the report traces to the activity-data and emission-factor
// tables it contains, so a third-party assurer can verify it.

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// Brand palette (forest green).
var (
	brandDark  = [3]int{29, 59, 46}   // #1d3b2e
	brandMid   = [3]int{47, 107, 80}  // #2f6b50
	inkColor   = [3]int{22, 32, 27}   // #16201b
	mutedColor = [3]int{106, 122, 113} // #6a7a71
	lineColor  = [3]int{221, 227, 222} // #dde3de
	zebraColor = [3]int{247, 248, 246} // #f7f8f6
)

const (
	pageW   = 210.0
	marginX = 15.0
	usableW = pageW - 2*marginX
)

// ExportInventoryReportPDF renders the full report and returns the PDF bytes.
func ExportInventoryReportPDF(inv *InventoryReport) ([]byte, error) {
	orgName := inv.OrgName
	if strings.TrimSpace(orgName) == "" {
		orgName = "Your Organization"
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(fmt.Sprintf("GHG Emissions Inventory %d - %s", inv.Year, orgName), false)
	pdf.SetAuthor("OffGridFlow", false)
	pdf.AliasNbPages("")
	pdf.SetMargins(marginX, 18, marginX)
	pdf.SetAutoPageBreak(true, 20)

	// Repeating footer on every page.
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "", 7.5)
		setColor(pdf, mutedColor)
		pdf.CellFormat(0, 5, fmt.Sprintf("Generated by OffGridFlow  |  %s  |  GHG Protocol Corporate Standard  |  %s",
			orgName, inv.GeneratedAt.Format("2 Jan 2006")), "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d of {nb}", pdf.PageNo()), "", 0, "R", false, 0, "")
	})

	renderCover(pdf, inv, orgName)

	// Content pages start here.
	pdf.AddPage()
	renderEntity(pdf, inv, orgName)
	renderExecutiveSummary(pdf, inv)
	renderMethodology(pdf, inv)
	renderByCategory(pdf, inv)
	renderByLocation(pdf, inv)
	renderFactors(pdf, inv)
	renderActivityData(pdf, inv)
	renderDataQuality(pdf, inv)
	renderAssurance(pdf, inv, orgName)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("pdf export: %w", err)
	}
	return buf.Bytes(), nil
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

func renderCover(pdf *gofpdf.Fpdf, inv *InventoryReport, orgName string) {
	pdf.AddPage()

	// Top brand band.
	setFill(pdf, brandDark)
	pdf.Rect(0, 0, pageW, 70, "F")
	pdf.SetY(24)
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(160, 210, 180)
	pdf.CellFormat(0, 7, "OFFGRIDFLOW  |  GHG EMISSIONS INVENTORY", "", 1, "L", false, 0, "")
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "B", 26)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(0, 14, "Greenhouse Gas", "", 1, "L", false, 0, "")
	pdf.SetX(marginX)
	pdf.CellFormat(0, 14, "Emissions Inventory Report", "", 1, "L", false, 0, "")

	pdf.SetY(88)
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "", 11)
	setColor(pdf, mutedColor)
	pdf.CellFormat(0, 6, "Prepared for", "", 1, "L", false, 0, "")
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "B", 20)
	setColor(pdf, inkColor)
	pdf.CellFormat(0, 11, orgName, "", 1, "L", false, 0, "")

	pdf.Ln(6)
	coverRow(pdf, "Reporting period", fmt.Sprintf("1 January - 31 December %d", inv.Year))
	coverRow(pdf, "Reporting standard", "GHG Protocol Corporate Accounting & Reporting Standard")
	coverRow(pdf, "Regulatory basis", "California SB 253 - Climate Corporate Data Accountability Act")
	coverRow(pdf, "Report generated", inv.GeneratedAt.Format("2 January 2006, 15:04 MST"))

	// Headline total in a card.
	pdf.SetY(160)
	pdf.SetX(marginX)
	setFill(pdf, zebraColor)
	setDraw(pdf, lineColor)
	pdf.Rect(marginX, 160, usableW, 34, "FD")
	pdf.SetXY(marginX+8, 168)
	pdf.SetFont("Helvetica", "", 11)
	setColor(pdf, mutedColor)
	pdf.CellFormat(0, 6, "Total reported emissions", "", 1, "L", false, 0, "")
	pdf.SetXY(marginX+8, 175)
	pdf.SetFont("Helvetica", "B", 24)
	setColor(pdf, brandMid)
	pdf.CellFormat(0, 12, fmt.Sprintf("%s  tCO2e", fmtT(inv.TotalTonnes)), "", 1, "L", false, 0, "")

	pdf.SetY(210)
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "I", 8.5)
	setColor(pdf, mutedColor)
	pdf.MultiCell(usableW, 4.5, "This report presents a greenhouse gas emissions inventory prepared using the GHG Protocol Corporate Standard. Figures are self-reported based on activity data supplied by the organization and are structured to support third-party limited assurance as required under California SB 253. This document is not itself an assurance opinion.", "", "L", false)
}

func coverRow(pdf *gofpdf.Fpdf, label, value string) {
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, mutedColor)
	pdf.CellFormat(45, 7, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, inkColor)
	pdf.CellFormat(usableW-45, 7, value, "", 1, "L", false, 0, "")
}

func renderEntity(pdf *gofpdf.Fpdf, inv *InventoryReport, orgName string) {
	sectionTitle(pdf, "1", "Reporting Entity & Organizational Boundaries")
	keyVal(pdf, "Reporting entity", orgName)
	keyVal(pdf, "Reporting period", fmt.Sprintf("1 January - 31 December %d", inv.Year))
	keyVal(pdf, "Consolidation approach", "Operational control")
	keyVal(pdf, "Reporting standard", "GHG Protocol Corporate Accounting & Reporting Standard (revised)")
	keyVal(pdf, "Gases covered", "CO2, CH4, N2O and other Kyoto gases, expressed as CO2e (100-yr GWP)")
	bodyText(pdf, "The organizational boundary is defined using the operational control approach: emissions from operations over which the entity has the authority to introduce and implement its operating policies are consolidated at 100%. Emissions are classified into Scope 1 (direct), Scope 2 (purchased energy) and Scope 3 (value chain) in accordance with the GHG Protocol.")
}

func renderExecutiveSummary(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	sectionTitle(pdf, "2", "Executive Summary")
	bodyText(pdf, fmt.Sprintf("For the %d reporting year, %s and its consolidated operations reported total greenhouse gas emissions of %s tonnes of CO2 equivalent (tCO2e), disaggregated by scope below.", inv.Year, orNoun(inv.OrgName), fmtT(inv.TotalTonnes)))

	th := []string{"Scope", "Emissions (tCO2e)", "Share"}
	widths := []float64{90, 55, usableW - 145}
	tableHead(pdf, th, widths)
	rows := [][3]string{
		{"Scope 1 - Direct", fmtT(inv.Scope1Tonnes), pct(inv.Scope1Tonnes, inv.TotalTonnes)},
		{"Scope 2 - Energy indirect", fmtT(inv.Scope2Tonnes), pct(inv.Scope2Tonnes, inv.TotalTonnes)},
		{"Scope 3 - Value chain", fmtT(inv.Scope3Tonnes), pct(inv.Scope3Tonnes, inv.TotalTonnes)},
	}
	for i, r := range rows {
		tableRow3(pdf, r, widths, i%2 == 1, false)
	}
	tableRow3(pdf, [3]string{"Total", fmtT(inv.TotalTonnes), "100%"}, widths, false, true)
}

func renderMethodology(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	sectionTitle(pdf, "3", "Methodology")
	bodyText(pdf, "Emissions were quantified using the activity-based method defined by the GHG Protocol Corporate Standard: each activity's emissions equal its activity data multiplied by a published emission factor for the relevant scope, region and category.")
	bulletText(pdf, "Calculation: Emissions (kgCO2e) = Activity data x Emission factor.")
	bulletText(pdf, "Scope 2 electricity uses the location-based method with US EPA eGRID grid-average factors.")
	bulletText(pdf, "Scope 1 fuel combustion uses US EPA GHG Emission Factors Hub factors.")
	bulletText(pdf, "Scope 3 uses activity-based factors (transport) and spend-based EEIO factors where activity data is unavailable.")
	bulletText(pdf, "Global Warming Potentials follow the IPCC 100-year time horizon; results are expressed as CO2e.")

	if len(inv.Factors) > 0 {
		srcSet := map[string]bool{}
		var srcs []string
		for _, f := range inv.Factors {
			if !srcSet[f.Source] {
				srcSet[f.Source] = true
				srcs = append(srcs, f.Source)
			}
		}
		bodyText(pdf, "Emission factor sources used in this inventory: "+strings.Join(srcs, "; ")+". A complete factor-by-factor audit trail is provided in Section 6.")
	}
}

func renderByCategory(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	if len(inv.ByCategory) == 0 {
		return
	}
	sectionTitle(pdf, "4", "Emissions by Source Category")
	th := []string{"Category", "Scope", "Emissions (tCO2e)", "Share"}
	widths := []float64{80, 25, 45, usableW - 150}
	tableHead(pdf, th, widths)
	for i, c := range inv.ByCategory {
		row := []string{titleCase(c.Label), fmt.Sprintf("%d", c.Scope), fmtT(c.Tonnes), fmt.Sprintf("%.1f%%", c.Percent)}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderByLocation(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	if len(inv.ByLocation) <= 1 {
		return
	}
	sectionTitle(pdf, "5", "Emissions by Location")
	th := []string{"Location", "Emissions (tCO2e)", "Share"}
	widths := []float64{95, 50, usableW - 145}
	tableHead(pdf, th, widths)
	for i, c := range inv.ByLocation {
		row := []string{c.Label, fmtT(c.Tonnes), fmt.Sprintf("%.1f%%", c.Percent)}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderFactors(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	if len(inv.Factors) == 0 {
		return
	}
	sectionTitle(pdf, "6", "Emission Factors & Audit Trail")
	bodyText(pdf, "Every emission factor applied in this inventory is listed below with its published source, supporting third-party verification.")
	th := []string{"Sc.", "Category", "Factor", "Unit", "Source"}
	widths := []float64{10, 42, 22, 20, usableW - 94}
	tableHead(pdf, th, widths)
	for i, f := range inv.Factors {
		row := []string{
			fmt.Sprintf("%d", f.Scope),
			titleCase(f.Category),
			fmt.Sprintf("%.4g", f.Value),
			factorUnit(f),
			f.Source,
		}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderActivityData(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	if len(inv.LineItems) == 0 {
		return
	}
	sectionTitle(pdf, "7", "Activity Data")
	bodyText(pdf, "The underlying activity records used to calculate this inventory. Each row is one measured activity and its resulting emissions.")
	th := []string{"Sc.", "Category", "Location", "Quantity", "Unit", "tCO2e"}
	widths := []float64{10, 46, 42, 30, 20, usableW - 148}
	tableHead(pdf, th, widths)
	for i, li := range inv.LineItems {
		row := []string{
			fmt.Sprintf("%d", li.Scope),
			titleCase(li.Category),
			truncStr(li.Location, 26),
			fmtNum(li.Quantity),
			li.Unit,
			fmtT(li.EmissionsTonnes),
		}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderDataQuality(pdf *gofpdf.Fpdf, inv *InventoryReport) {
	sectionTitle(pdf, "8", "Data Quality & Completeness")
	keyVal(pdf, "Activity records", fmt.Sprintf("%d", inv.TotalActivities))
	keyVal(pdf, "Complete records", fmt.Sprintf("%d of %d", inv.CompleteActivities, inv.TotalActivities))
	keyVal(pdf, "Completeness", fmt.Sprintf("%.0f%%", inv.CompletenessPct))
	keyVal(pdf, "Distinct emission factors", fmt.Sprintf("%d", len(inv.Factors)))
	if len(inv.Warnings) > 0 {
		pdf.Ln(2)
		pdf.SetFont("Helvetica", "B", 10)
		setColor(pdf, inkColor)
		pdf.CellFormat(0, 6, "Notes & limitations on data quality:", "", 1, "L", false, 0, "")
		for _, w := range inv.Warnings {
			bulletText(pdf, w)
		}
	}
}

func renderAssurance(pdf *gofpdf.Fpdf, inv *InventoryReport, orgName string) {
	sectionTitle(pdf, "9", "Assurance & Limitations")
	bodyText(pdf, fmt.Sprintf("This greenhouse gas inventory was prepared by %s using OffGridFlow, applying the GHG Protocol Corporate Accounting and Reporting Standard. The figures are self-reported and based on activity data supplied by the organization.", orNoun(orgName)))
	bodyText(pdf, "California SB 253 (the Climate Corporate Data Accountability Act) requires covered entities to obtain third-party assurance of their reported emissions - limited assurance for Scope 1 and Scope 2, phasing to reasonable assurance, with Scope 3 assurance following. This report is structured to support that assurance: it provides the organizational boundary, methodology, a complete emission-factor audit trail, and the underlying activity data required by an assurance provider.")
	bodyText(pdf, "This document does not itself constitute an assurance opinion, legal advice, or a regulatory filing. The organization is responsible for the completeness and accuracy of the input data and for engaging a qualified third-party assurance provider prior to submission.")

	pdf.Ln(4)
	setDraw(pdf, lineColor)
	pdf.Line(marginX, pdf.GetY(), marginX+usableW, pdf.GetY())
	pdf.Ln(4)
	pdf.SetFont("Helvetica", "", 9)
	setColor(pdf, mutedColor)
	pdf.MultiCell(usableW, 5, fmt.Sprintf("Report reference: OGF-%s-%d  |  Generated %s  |  Prepared with OffGridFlow (GHG Protocol Corporate Standard).",
		shortID(inv.OrgID), inv.Year, inv.GeneratedAt.Format(time.RFC3339)), "", "L", false)
}

// ---------------------------------------------------------------------------
// Layout helpers
// ---------------------------------------------------------------------------

func sectionTitle(pdf *gofpdf.Fpdf, num, title string) {
	if pdf.GetY() > 245 {
		pdf.AddPage()
	}
	pdf.Ln(6)
	setFill(pdf, brandMid)
	y := pdf.GetY()
	pdf.Rect(marginX, y, 3, 7, "F")
	pdf.SetX(marginX + 6)
	pdf.SetFont("Helvetica", "B", 13.5)
	setColor(pdf, brandDark)
	pdf.CellFormat(0, 7, fmt.Sprintf("%s.  %s", num, title), "", 1, "L", false, 0, "")
	pdf.Ln(2)
}

func bodyText(pdf *gofpdf.Fpdf, txt string) {
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, inkColor)
	pdf.MultiCell(usableW, 5.2, txt, "", "L", false)
	pdf.Ln(1.5)
}

func bulletText(pdf *gofpdf.Fpdf, txt string) {
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, brandMid)
	pdf.SetX(marginX)
	pdf.CellFormat(5, 5.2, "-", "", 0, "L", false, 0, "")
	setColor(pdf, inkColor)
	pdf.MultiCell(usableW-5, 5.2, txt, "", "L", false)
}

func keyVal(pdf *gofpdf.Fpdf, k, v string) {
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, mutedColor)
	pdf.CellFormat(55, 6.5, k, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, inkColor)
	pdf.MultiCell(usableW-55, 6.5, v, "", "L", false)
}

func tableHead(pdf *gofpdf.Fpdf, headers []string, widths []float64) {
	if pdf.GetY() > 250 {
		pdf.AddPage()
	}
	pdf.SetFont("Helvetica", "B", 9)
	setFill(pdf, brandDark)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetX(marginX)
	for i, h := range headers {
		align := "L"
		if i > 0 && i >= len(headers)-2 {
			align = "R"
		}
		pdf.CellFormat(widths[i], 7, h, "", 0, align, true, 0, "")
	}
	pdf.Ln(7)
}

func tableRow3(pdf *gofpdf.Fpdf, cells [3]string, widths []float64, zebra, total bool) {
	tableRowN(pdf, cells[:], widths, zebra, total)
}

func tableRowN(pdf *gofpdf.Fpdf, cells []string, widths []float64, zebra, total bool) {
	rowH := 6.5
	if pdf.GetY()+rowH > 275 {
		pdf.AddPage()
	}
	fill := false
	if total {
		pdf.SetFont("Helvetica", "B", 9)
		setFill(pdf, [3]int{234, 240, 236})
		fill = true
	} else {
		pdf.SetFont("Helvetica", "", 9)
		if zebra {
			setFill(pdf, zebraColor)
			fill = true
		}
	}
	setColor(pdf, inkColor)
	pdf.SetX(marginX)
	for i, c := range cells {
		align := "L"
		if i > 0 && i >= len(cells)-2 {
			align = "R"
		}
		pdf.CellFormat(widths[i], rowH, c, "", 0, align, fill, 0, "")
	}
	pdf.Ln(rowH)
}

// ---------------------------------------------------------------------------
// Small utilities
// ---------------------------------------------------------------------------

func setColor(pdf *gofpdf.Fpdf, c [3]int) { pdf.SetTextColor(c[0], c[1], c[2]) }
func setFill(pdf *gofpdf.Fpdf, c [3]int)  { pdf.SetFillColor(c[0], c[1], c[2]) }
func setDraw(pdf *gofpdf.Fpdf, c [3]int)  { pdf.SetDrawColor(c[0], c[1], c[2]) }

// fmtT formats tonnes with thousands separators and 2 decimals.
func fmtT(f float64) string { return withCommas(fmt.Sprintf("%.2f", f)) }

// fmtNum formats a quantity, dropping trailing zeros for whole numbers.
func fmtNum(f float64) string {
	if f == float64(int64(f)) {
		return withCommas(fmt.Sprintf("%d", int64(f)))
	}
	return withCommas(fmt.Sprintf("%.2f", f))
}

func withCommas(s string) string {
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	intPart, frac := s, ""
	if i := strings.IndexByte(s, '.'); i >= 0 {
		intPart, frac = s[:i], s[i:]
	}
	n := len(intPart)
	if n <= 3 {
		return sign(neg) + intPart + frac
	}
	var b strings.Builder
	pre := n % 3
	if pre > 0 {
		b.WriteString(intPart[:pre])
		if n > pre {
			b.WriteByte(',')
		}
	}
	for i := pre; i < n; i += 3 {
		b.WriteString(intPart[i : i+3])
		if i+3 < n {
			b.WriteByte(',')
		}
	}
	return sign(neg) + b.String() + frac
}

func sign(neg bool) string {
	if neg {
		return "-"
	}
	return ""
}

func pct(part, whole float64) string {
	if whole == 0 {
		return "0%"
	}
	return fmt.Sprintf("%.1f%%", part/whole*100)
}

func titleCase(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "_", " "), "-", " ")
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	if len(words) == 0 {
		return s
	}
	return strings.Join(words, " ")
}

func truncStr(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "..."
}

func factorUnit(f FactorRef) string {
	if f.Unit == "" {
		return "per unit"
	}
	return "kg/" + f.Unit
}

func orNoun(orgName string) string {
	if strings.TrimSpace(orgName) == "" {
		return "the organization"
	}
	return orgName
}

func shortID(id string) string {
	id = strings.ReplaceAll(id, "-", "")
	if len(id) > 8 {
		return strings.ToUpper(id[:8])
	}
	if id == "" {
		return "ORG"
	}
	return strings.ToUpper(id)
}
