package compliance

// report_pdf.go renders an InventoryReport into an audit-ready, assurance-grade
// PDF structured for California SB 253 / the GHG Protocol Corporate Standard.
// Every figure in the report traces to the activity-data and emission-factor
// tables it contains, so a third-party assurer can verify it.

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// Brand palette (forest green).
var (
	brandDark  = [3]int{29, 59, 46}   // #1d3b2e
	brandMid   = [3]int{47, 107, 80}  // #2f6b50
	inkColor   = [3]int{22, 32, 27}   // #16201b
	mutedColor = [3]int{106, 122, 113} // #6a7a71
	lineColor  = [3]int{221, 227, 222} // #dde3de
	zebraColor = [3]int{247, 248, 246} // #f7f8f6
)

const (
	pageW   = 210.0
	marginX = 15.0
	usableW = pageW - 2*marginX
)

// ExportInventoryReportPDF renders the full report and returns the PDF bytes.
func ExportInventoryReportPDF(inv *InventoryReport) ([]byte, error) {
	orgName := inv.OrgName
	if strings.TrimSpace(orgName) == "" {
		orgName = "Your Organization"
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(fmt.Sprintf("GHG Emissions Inventory %d - %s", inv.Year, orgName), false)
	pdf.SetAuthor("OffGridFlow", false)
	pdf.AliasNbPages("")
	pdf.SetMargins(marginX, 18, marginX)
	pdf.SetAutoPageBreak(true, 20)

	// Repeating footer on every page.
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "", 7.5)
		setColor(pdf, mutedColor)
		pdf.CellFormat(0, 5, fmt.Sprintf("Generated by OffGridFlow  |  %s  |  GHG Protocol Corporate Standard  |  %s",
			orgName, inv.GeneratedAt.Format("2 Jan 2006")), "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d of {nb}", pdf.PageNo()), "", 0, "R", false, 0, "")
	})

	renderCover(pdf, inv, orgName)

	// Content pages start here. Sections auto-number via the shared counter so
	// conditional sections never leave a gap.
	pdf.AddPage()
	sec := 0
	renderEntity(pdf, &sec, inv, orgName)
	renderExecutiveSummary(pdf, &sec, inv)
	renderScope1Gases(pdf, &sec, inv)
	renderScope2Dual(pdf, &sec, inv)
	renderMethodology(pdf, &sec, inv)
	renderByCategory(pdf, &sec, inv)
	renderByLocation(pdf, &sec, inv)
	renderScope3Coverage(pdf, &sec, inv)
	renderBaseYear(pdf, &sec, inv)
	renderFactors(pdf, &sec, inv)
	renderActivityData(pdf, &sec, inv)
	renderDataQuality(pdf, &sec, inv)
	renderAssurance(pdf, &sec, inv, orgName)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("pdf export: %w", err)
	}
	return buf.Bytes(), nil
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

func renderCover(pdf *gofpdf.Fpdf, inv *InventoryReport, orgName string) {
	pdf.AddPage()

	// Top brand band.
	setFill(pdf, brandDark)
	pdf.Rect(0, 0, pageW, 70, "F")
	pdf.SetY(24)
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(160, 210, 180)
	pdf.CellFormat(0, 7, "OFFGRIDFLOW  |  GHG EMISSIONS INVENTORY", "", 1, "L", false, 0, "")
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "B", 26)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(0, 14, "Greenhouse Gas", "", 1, "L", false, 0, "")
	pdf.SetX(marginX)
	pdf.CellFormat(0, 14, "Emissions Inventory Report", "", 1, "L", false, 0, "")

	pdf.SetY(88)
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "", 11)
	setColor(pdf, mutedColor)
	pdf.CellFormat(0, 6, "Prepared for", "", 1, "L", false, 0, "")
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "B", 20)
	setColor(pdf, inkColor)
	pdf.CellFormat(0, 11, orgName, "", 1, "L", false, 0, "")

	pdf.Ln(6)
	coverRow(pdf, "Reporting period", fmt.Sprintf("1 January - 31 December %d", inv.Year))
	coverRow(pdf, "Reporting standard", "GHG Protocol Corporate Accounting & Reporting Standard")
	coverRow(pdf, "Regulatory basis", "California SB 253 - Climate Corporate Data Accountability Act")
	coverRow(pdf, "Report generated", inv.GeneratedAt.Format("2 January 2006, 15:04 MST"))

	// Headline total in a card.
	pdf.SetY(160)
	pdf.SetX(marginX)
	setFill(pdf, zebraColor)
	setDraw(pdf, lineColor)
	pdf.Rect(marginX, 160, usableW, 34, "FD")
	pdf.SetXY(marginX+8, 168)
	pdf.SetFont("Helvetica", "", 11)
	setColor(pdf, mutedColor)
	pdf.CellFormat(0, 6, "Total reported emissions", "", 1, "L", false, 0, "")
	pdf.SetXY(marginX+8, 175)
	pdf.SetFont("Helvetica", "B", 24)
	setColor(pdf, brandMid)
	pdf.CellFormat(0, 12, fmt.Sprintf("%s  tCO2e", fmtT(inv.TotalTonnes)), "", 1, "L", false, 0, "")

	pdf.SetY(210)
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "I", 8.5)
	setColor(pdf, mutedColor)
	pdf.MultiCell(usableW, 4.5, "This report presents a greenhouse gas emissions inventory prepared using the GHG Protocol Corporate Standard. Figures are self-reported based on activity data supplied by the organization and are structured to support third-party limited assurance as required under California SB 253. This document is not itself an assurance opinion.", "", "L", false)
}

func coverRow(pdf *gofpdf.Fpdf, label, value string) {
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, mutedColor)
	pdf.CellFormat(45, 7, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, inkColor)
	pdf.CellFormat(usableW-45, 7, value, "", 1, "L", false, 0, "")
}

func renderEntity(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport, orgName string) {
	sectionTitle(pdf, sec, "Reporting Entity & Organizational Boundaries")
	keyVal(pdf, "Reporting entity", orgName)
	keyVal(pdf, "Reporting period", fmt.Sprintf("1 January - 31 December %d", inv.Year))
	keyVal(pdf, "Consolidation approach", "Operational control")
	keyVal(pdf, "Reporting standard", "GHG Protocol Corporate Accounting & Reporting Standard (revised)")
	keyVal(pdf, "Gases covered", "CO2, CH4, N2O, HFCs, PFCs, SF6, NF3 (7 Kyoto gases), expressed as CO2e")
	bodyText(pdf, "The organizational boundary is defined using the operational control approach: emissions from operations over which the entity has the authority to introduce and implement its operating policies are consolidated at 100%. Emissions are classified into Scope 1 (direct), Scope 2 (purchased energy) and Scope 3 (value chain) in accordance with the GHG Protocol.")
}

func renderExecutiveSummary(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	sectionTitle(pdf, sec, "Executive Summary")
	bodyText(pdf, fmt.Sprintf("For the %d reporting year, %s and its consolidated operations reported total greenhouse gas emissions of %s tonnes of CO2 equivalent (tCO2e), disaggregated by scope below.", inv.Year, orNoun(inv.OrgName), fmtT(inv.TotalTonnes)))

	th := []string{"Scope", "Emissions (tCO2e)", "Share"}
	widths := []float64{90, 55, usableW - 145}
	tableHead(pdf, th, widths)
	rows := [][3]string{
		{"Scope 1 - Direct", fmtT(inv.Scope1Tonnes), pct(inv.Scope1Tonnes, inv.TotalTonnes)},
		{"Scope 2 - Energy indirect", fmtT(inv.Scope2Tonnes), pct(inv.Scope2Tonnes, inv.TotalTonnes)},
		{"Scope 3 - Value chain", fmtT(inv.Scope3Tonnes), pct(inv.Scope3Tonnes, inv.TotalTonnes)},
	}
	for i, r := range rows {
		tableRow3(pdf, r, widths, i%2 == 1, false)
	}
	tableRow3(pdf, [3]string{"Total", fmtT(inv.TotalTonnes), "100%"}, widths, false, true)
}

func renderScope1Gases(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	if inv.Scope1Tonnes <= 0 {
		return
	}
	g := inv.Scope1Gases
	sectionTitle(pdf, sec, "Scope 1 Emissions by Greenhouse Gas")
	bodyText(pdf, "The GHG Protocol requires the seven Kyoto gases to be reported. Scope 1 combustion emissions are disaggregated into CO2, CH4 and N2O below, expressed as CO2e using IPCC AR6 100-year GWPs (CH4 fossil = 29.8, N2O = 273). The industrial gases (HFCs, PFCs, SF6, NF3) arise from fugitive/process sources; none were reported in this inventory.")

	th := []string{"Greenhouse gas", "Emissions (tCO2e)", "Share of Scope 1"}
	widths := []float64{90, 45, usableW - 135}
	tableHead(pdf, th, widths)
	rows := [][3]string{
		{"Carbon dioxide (CO2)", fmtT(g.CO2), pct(g.CO2, inv.Scope1Tonnes)},
		{"Methane (CH4)", fmtT(g.CH4), pct(g.CH4, inv.Scope1Tonnes)},
		{"Nitrous oxide (N2O)", fmtT(g.N2O), pct(g.N2O, inv.Scope1Tonnes)},
		{"Hydrofluorocarbons (HFCs)", fmtT(g.HFCs), pct(g.HFCs, inv.Scope1Tonnes)},
		{"Perfluorocarbons (PFCs)", fmtT(g.PFCs), pct(g.PFCs, inv.Scope1Tonnes)},
		{"Sulfur hexafluoride (SF6)", fmtT(g.SF6), pct(g.SF6, inv.Scope1Tonnes)},
		{"Nitrogen trifluoride (NF3)", fmtT(g.NF3), pct(g.NF3, inv.Scope1Tonnes)},
	}
	for i, r := range rows {
		tableRow3(pdf, r, widths, i%2 == 1, false)
	}
	tableRow3(pdf, [3]string{"Total Scope 1 (fossil)", fmtT(g.Total()), "100%"}, widths, false, true)

	note := "The combustion split uses representative fossil-fuel gas shares (CO2-dominant); for third-party assurance, apply fuel- and technology-specific gas factors (EPA GHG Emission Factors Hub / IPCC)."
	if g.Biogenic > 0 {
		note += fmt.Sprintf(" Biogenic CO2 of %s tCO2e (from biofuels) is reported separately and excluded from the Scope 1 fossil total, per the GHG Protocol.", fmtT(g.Biogenic))
	} else {
		note += " No biogenic CO2 (from biofuels) was reported; it would be disclosed separately where present."
	}
	bodyText(pdf, note)
}

func renderScope2Dual(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	// Only meaningful when there is Scope 2 electricity in the inventory.
	if inv.Scope2Tonnes <= 0 {
		return
	}
	sectionTitle(pdf, sec, "Scope 2 Dual Reporting (Location & Market-Based)")
	bodyText(pdf, "The GHG Protocol Scope 2 Guidance requires purchased-electricity emissions to be reported under both methods: the location-based method (grid-average emission factors) and the market-based method (contractual instruments such as supplier-specific factors, renewable energy certificates, guarantees of origin, or power purchase agreements). Both are presented below.")

	th := []string{"Scope 2 method", "Emissions (tCO2e)"}
	widths := []float64{usableW - 55, 55}
	tableHead(pdf, th, widths)
	tableRowN(pdf, []string{"Location-based (grid average)", fmtT(inv.Scope2Tonnes)}, widths, false, false)
	tableRowN(pdf, []string{"Market-based (contractual)", fmtT(inv.Scope2MarketTonnes)}, widths, true, false)

	if inv.HasMarketData {
		reduction := inv.Scope2Tonnes - inv.Scope2MarketTonnes
		bodyText(pdf, fmt.Sprintf("Market-based emissions reflect the supplier/contractual emission factors and renewable coverage supplied per account, a reduction of %s tCO2e versus location-based. Offsets, if any, are excluded from both figures and disclosed separately.", fmtT(reduction)))
	} else {
		bodyText(pdf, "No contractual instruments (supplier-specific emission factors or renewable/REC coverage) were supplied for the reporting period; the market-based figure therefore equals the location-based figure. To reflect green procurement, provide a per-account supplier emission factor (kgCO2e/kWh) or a renewable share with your electricity data.")
	}
}

func renderMethodology(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	sectionTitle(pdf, sec, "Methodology")
	bodyText(pdf, "Emissions were quantified using the activity-based method defined by the GHG Protocol Corporate Standard: each activity's emissions equal its activity data multiplied by a published emission factor for the relevant scope, region and category.")

	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, inkColor)
	pdf.CellFormat(0, 6, "Calculation formulae applied:", "", 1, "L", false, 0, "")
	bulletText(pdf, "General: Emissions (tCO2e) = Sum( Activity data x Emission factor x GWP ).")
	bulletText(pdf, "Scope 1 (combustion): Sum( Fuel consumed x Fuel emission factor ). Fuel-specific factors bundle CO2, CH4 and N2O expressed as CO2e.")
	bulletText(pdf, "Scope 2 (location-based): Sum( Electricity (kWh) x Grid-average emission factor ), using US EPA eGRID grid factors.")
	bulletText(pdf, "Scope 3 travel: Sum( Distance x Mode-specific factor ). Scope 3 spend: Sum( Spend x EEIO factor ).")

	pdf.Ln(1)
	keyVal(pdf, "Global Warming Potentials", "IPCC Sixth Assessment Report (AR6), 100-year time horizon (GWP-100)")
	keyVal(pdf, "Scope 2 methods", "Dual reporting: location-based and market-based (see Scope 2 Dual Reporting section)")
	bodyText(pdf, "Biofuels (e.g. biodiesel, ethanol, sustainably-sourced wood) are treated as carbon-neutral at the point of combustion per the GHG Protocol; biogenic CO2 is excluded from Scope 1 totals and reported separately where present. Emission factors are representative published values from the sources cited; for third-party assurance, confirm the specific factor vintage applicable to the reporting period.")

	if len(inv.Factors) > 0 {
		srcSet := map[string]bool{}
		var srcs []string
		for _, f := range inv.Factors {
			if !srcSet[f.Source] {
				srcSet[f.Source] = true
				srcs = append(srcs, f.Source)
			}
		}
		bodyText(pdf, "Emission factor sources used in this inventory: "+strings.Join(srcs, "; ")+". A complete factor-by-factor audit trail is provided in a later section.")
	}
}

func renderByCategory(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	if len(inv.ByCategory) == 0 {
		return
	}
	sectionTitle(pdf, sec, "Emissions by Source Category")
	th := []string{"Category", "Scope", "Emissions (tCO2e)", "Share"}
	widths := []float64{80, 25, 45, usableW - 150}
	tableHead(pdf, th, widths)
	for i, c := range inv.ByCategory {
		row := []string{titleCase(c.Label), fmt.Sprintf("%d", c.Scope), fmtT(c.Tonnes), fmt.Sprintf("%.1f%%", c.Percent)}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderByLocation(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	if len(inv.ByLocation) <= 1 {
		return
	}
	sectionTitle(pdf, sec, "Emissions by Location")
	th := []string{"Location", "Emissions (tCO2e)", "Share"}
	widths := []float64{95, 50, usableW - 145}
	tableHead(pdf, th, widths)
	for i, c := range inv.ByLocation {
		row := []string{c.Label, fmtT(c.Tonnes), fmt.Sprintf("%.1f%%", c.Percent)}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderScope3Coverage(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	if len(inv.Scope3Coverage) == 0 {
		return
	}
	sectionTitle(pdf, sec, "Scope 3 Category Coverage")
	bodyText(pdf, "The GHG Protocol defines 15 Scope 3 categories. Each is assessed below; categories not reported are those for which activity data was not provided for this reporting period and are candidates for future inclusion.")
	th := []string{"#", "Category", "Status", "tCO2e"}
	widths := []float64{10, 108, 32, usableW - 150}
	tableHead(pdf, th, widths)
	for i, c := range inv.Scope3Coverage {
		status := "Not reported"
		val := "-"
		if c.Reported {
			status = "Reported"
			val = fmtT(c.Tonnes)
		}
		tableRowN(pdf, []string{fmt.Sprintf("%d", c.Number), c.Name, status, val}, widths, i%2 == 1, false)
	}
	bodyText(pdf, "Exclusion basis: categories marked 'Not reported' are excluded due to unavailable primary activity data, not immateriality. Their relevance should be reassessed as data collection matures, consistent with GHG Protocol completeness.")
}

func renderBaseYear(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	sectionTitle(pdf, sec, "Base Year & Emissions Intensity")
	keyVal(pdf, "Base year", fmt.Sprintf("%d", inv.BaseYear))
	keyVal(pdf, "Base year rationale", "First greenhouse gas inventory; established as the base year for future tracking")
	keyVal(pdf, "Base year total", fmt.Sprintf("%s tCO2e", fmtT(inv.TotalTonnes)))
	bodyText(pdf, "Under the GHG Protocol, a base year is fixed as the reference against which future emissions are compared. It will be recalculated for significant structural changes (acquisitions, divestitures, or methodology changes) exceeding the entity's significance threshold.")

	perRev := inv.IntensityPerRevenueMM()
	perFTE := inv.IntensityPerEmployee()
	if perRev > 0 || perFTE > 0 {
		bodyText(pdf, "Emissions intensity normalizes total emissions against a measure of business activity, enabling comparison across years and peers independent of absolute growth.")
		th := []string{"Emissions intensity metric", "Value (tCO2e)"}
		widths := []float64{usableW - 55, 55}
		tableHead(pdf, th, widths)
		zebra := false
		if perRev > 0 {
			keyVal(pdf, "Annual revenue", "$"+withCommas(fmt.Sprintf("%.0f", inv.Revenue)))
			tableRowN(pdf, []string{"Per $1M revenue", fmtT(perRev)}, widths, zebra, false)
			zebra = !zebra
		}
		if perFTE > 0 {
			keyVal(pdf, "Full-time-equivalent headcount", withCommas(fmt.Sprintf("%d", inv.Employees)))
			tableRowN(pdf, []string{"Per full-time-equivalent employee", fmtT(perFTE)}, widths, zebra, false)
		}
		bodyText(pdf, "Intensity is computed on the location-based total for the reporting period. Under California SB 253, revenue is also the threshold on which reporting applicability is assessed.")
	} else {
		bodyText(pdf, "Emissions intensity (tCO2e per unit of revenue, production, or FTE) is a required comparability metric. It is computed once a normalization denominator - typically annual revenue - is provided for the reporting period; provide revenue to enable intensity disclosure in future reports.")
	}
}

func renderFactors(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	if len(inv.Factors) == 0 {
		return
	}
	sectionTitle(pdf, sec, "Emission Factors & Audit Trail")
	bodyText(pdf, "Every emission factor applied in this inventory is listed below with its published source, supporting third-party verification.")
	th := []string{"Sc.", "Category", "Factor", "Unit", "Source"}
	widths := []float64{10, 42, 22, 20, usableW - 94}
	tableHead(pdf, th, widths)
	for i, f := range inv.Factors {
		row := []string{
			fmt.Sprintf("%d", f.Scope),
			titleCase(f.Category),
			fmt.Sprintf("%.4g", f.Value),
			factorUnit(f),
			f.Source,
		}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
}

func renderActivityData(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	if len(inv.LineItems) == 0 {
		return
	}
	sectionTitle(pdf, sec, "Activity Data")
	bodyText(pdf, "The underlying activity records used to calculate this inventory. Each row is one measured activity and its resulting emissions.")
	th := []string{"Sc.", "Category", "Location", "Quantity", "Unit", "tCO2e"}
	widths := []float64{10, 46, 42, 30, 20, usableW - 148}
	tableHead(pdf, th, widths)
	hasBiogenic := false
	for i, li := range inv.LineItems {
		cat := titleCase(li.Category)
		if li.Biogenic {
			cat += " (biogenic)"
			hasBiogenic = true
		}
		row := []string{
			fmt.Sprintf("%d", li.Scope),
			cat,
			truncStr(li.Location, 26),
			fmtNum(li.Quantity),
			li.Unit,
			fmtT(li.EmissionsTonnes),
		}
		tableRowN(pdf, row, widths, i%2 == 1, false)
	}
	if hasBiogenic {
		bodyText(pdf, "Rows marked (biogenic) are combustion of biofuels: their CO2 is reported as a separate biogenic memo item and is excluded from the fossil Scope 1 total shown elsewhere in this report, per the GHG Protocol.")
	}
}

func renderDataQuality(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport) {
	sectionTitle(pdf, sec, "Data Quality & Completeness")
	keyVal(pdf, "Activity records", fmt.Sprintf("%d", inv.TotalActivities))
	keyVal(pdf, "Complete records", fmt.Sprintf("%d of %d", inv.CompleteActivities, inv.TotalActivities))
	keyVal(pdf, "Completeness", fmt.Sprintf("%.0f%%", inv.CompletenessPct))
	keyVal(pdf, "Distinct emission factors", fmt.Sprintf("%d", len(inv.Factors)))
	if len(inv.Warnings) > 0 {
		pdf.Ln(2)
		pdf.SetFont("Helvetica", "B", 10)
		setColor(pdf, inkColor)
		pdf.CellFormat(0, 6, "Notes & limitations on data quality:", "", 1, "L", false, 0, "")
		for _, w := range inv.Warnings {
			bulletText(pdf, w)
		}
	}
}

func renderAssurance(pdf *gofpdf.Fpdf, sec *int, inv *InventoryReport, orgName string) {
	sectionTitle(pdf, sec, "Management Declaration, Assurance & Limitations")

	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, inkColor)
	pdf.CellFormat(0, 6, "Management responsibility statement", "", 1, "L", false, 0, "")
	bodyText(pdf, fmt.Sprintf("Management of %s is responsible for the preparation of this greenhouse gas inventory, for the completeness and accuracy of the underlying activity data, and for maintaining adequate internal controls over its GHG accounting. This inventory has been prepared in accordance with the GHG Protocol Corporate Accounting and Reporting Standard, applied consistently.", orNoun(orgName)))

	bodyText(pdf, "California SB 253 (the Climate Corporate Data Accountability Act) requires covered entities to obtain third-party assurance of their reported emissions - limited assurance for Scope 1 and Scope 2, phasing to reasonable assurance, with Scope 3 assurance following. This report is structured to support that assurance: it provides the organizational boundary, methodology and formulae, a complete emission-factor audit trail, Scope 3 category coverage, and the underlying activity data an assurance provider requires.")
	bodyText(pdf, "This document does not itself constitute an assurance opinion, legal advice, or a regulatory filing. The organization is responsible for the completeness and accuracy of the input data and for engaging a qualified third-party assurance provider prior to submission.")

	// Signature block.
	pdf.Ln(6)
	setDraw(pdf, [3]int{120, 130, 124})
	sigY := pdf.GetY() + 10
	pdf.Line(marginX, sigY, marginX+70, sigY)
	pdf.Line(marginX+95, sigY, marginX+95+55, sigY)
	pdf.SetY(sigY + 1)
	pdf.SetFont("Helvetica", "", 8.5)
	setColor(pdf, mutedColor)
	pdf.SetX(marginX)
	pdf.CellFormat(70, 5, "Authorized officer (signature)", "", 0, "L", false, 0, "")
	pdf.SetX(marginX + 95)
	pdf.CellFormat(55, 5, "Date", "", 1, "L", false, 0, "")
	pdf.Ln(2)
	pdf.SetX(marginX)
	pdf.CellFormat(70, 5, "Name / title: ______________________", "", 1, "L", false, 0, "")

	pdf.Ln(4)
	setDraw(pdf, lineColor)
	pdf.Line(marginX, pdf.GetY(), marginX+usableW, pdf.GetY())
	pdf.Ln(4)
	pdf.SetFont("Helvetica", "", 9)
	setColor(pdf, mutedColor)
	pdf.MultiCell(usableW, 5, fmt.Sprintf("Report reference: OGF-%s-%d  |  Generated %s  |  Prepared with OffGridFlow (GHG Protocol Corporate Standard).",
		shortID(inv.OrgID), inv.Year, inv.GeneratedAt.Format(time.RFC3339)), "", "L", false)
}

// ---------------------------------------------------------------------------
// Layout helpers
// ---------------------------------------------------------------------------

func sectionTitle(pdf *gofpdf.Fpdf, sec *int, title string) {
	*sec++
	if pdf.GetY() > 245 {
		pdf.AddPage()
	}
	pdf.Ln(6)
	setFill(pdf, brandMid)
	y := pdf.GetY()
	pdf.Rect(marginX, y, 3, 7, "F")
	pdf.SetX(marginX + 6)
	pdf.SetFont("Helvetica", "B", 13.5)
	setColor(pdf, brandDark)
	pdf.CellFormat(0, 7, fmt.Sprintf("%d.  %s", *sec, title), "", 1, "L", false, 0, "")
	pdf.Ln(2)
}

func bodyText(pdf *gofpdf.Fpdf, txt string) {
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, inkColor)
	pdf.MultiCell(usableW, 5.2, txt, "", "L", false)
	pdf.Ln(1.5)
}

func bulletText(pdf *gofpdf.Fpdf, txt string) {
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, brandMid)
	pdf.SetX(marginX)
	pdf.CellFormat(5, 5.2, "-", "", 0, "L", false, 0, "")
	setColor(pdf, inkColor)
	pdf.MultiCell(usableW-5, 5.2, txt, "", "L", false)
}

func keyVal(pdf *gofpdf.Fpdf, k, v string) {
	pdf.SetX(marginX)
	pdf.SetFont("Helvetica", "", 10)
	setColor(pdf, mutedColor)
	pdf.CellFormat(55, 6.5, k, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 10)
	setColor(pdf, inkColor)
	pdf.MultiCell(usableW-55, 6.5, v, "", "L", false)
}

func tableHead(pdf *gofpdf.Fpdf, headers []string, widths []float64) {
	if pdf.GetY() > 250 {
		pdf.AddPage()
	}
	pdf.SetFont("Helvetica", "B", 9)
	setFill(pdf, brandDark)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetX(marginX)
	for i, h := range headers {
		align := "L"
		if i > 0 && i >= len(headers)-2 {
			align = "R"
		}
		pdf.CellFormat(widths[i], 7, h, "", 0, align, true, 0, "")
	}
	pdf.Ln(7)
}

func tableRow3(pdf *gofpdf.Fpdf, cells [3]string, widths []float64, zebra, total bool) {
	tableRowN(pdf, cells[:], widths, zebra, total)
}

func tableRowN(pdf *gofpdf.Fpdf, cells []string, widths []float64, zebra, total bool) {
	rowH := 6.5
	if pdf.GetY()+rowH > 275 {
		pdf.AddPage()
	}
	fill := false
	if total {
		pdf.SetFont("Helvetica", "B", 9)
		setFill(pdf, [3]int{234, 240, 236})
		fill = true
	} else {
		pdf.SetFont("Helvetica", "", 9)
		if zebra {
			setFill(pdf, zebraColor)
			fill = true
		}
	}
	setColor(pdf, inkColor)
	pdf.SetX(marginX)
	for i, c := range cells {
		align := "L"
		if i > 0 && i >= len(cells)-2 {
			align = "R"
		}
		pdf.CellFormat(widths[i], rowH, c, "", 0, align, fill, 0, "")
	}
	pdf.Ln(rowH)
}

// ---------------------------------------------------------------------------
// Small utilities
// ---------------------------------------------------------------------------

func setColor(pdf *gofpdf.Fpdf, c [3]int) { pdf.SetTextColor(c[0], c[1], c[2]) }
func setFill(pdf *gofpdf.Fpdf, c [3]int)  { pdf.SetFillColor(c[0], c[1], c[2]) }
func setDraw(pdf *gofpdf.Fpdf, c [3]int)  { pdf.SetDrawColor(c[0], c[1], c[2]) }

// fmtT formats tonnes with thousands separators and 2 decimals.
func fmtT(f float64) string { return withCommas(fmt.Sprintf("%.2f", f)) }

// fmtNum formats a quantity, dropping trailing zeros for whole numbers.
func fmtNum(f float64) string {
	if f == float64(int64(f)) {
		return withCommas(fmt.Sprintf("%d", int64(f)))
	}
	return withCommas(fmt.Sprintf("%.2f", f))
}

func withCommas(s string) string {
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	intPart, frac := s, ""
	if i := strings.IndexByte(s, '.'); i >= 0 {
		intPart, frac = s[:i], s[i:]
	}
	n := len(intPart)
	if n <= 3 {
		return sign(neg) + intPart + frac
	}
	var b strings.Builder
	pre := n % 3
	if pre > 0 {
		b.WriteString(intPart[:pre])
		if n > pre {
			b.WriteByte(',')
		}
	}
	for i := pre; i < n; i += 3 {
		b.WriteString(intPart[i : i+3])
		if i+3 < n {
			b.WriteByte(',')
		}
	}
	return sign(neg) + b.String() + frac
}

func sign(neg bool) string {
	if neg {
		return "-"
	}
	return ""
}

func pct(part, whole float64) string {
	if whole == 0 {
		return "0%"
	}
	return fmt.Sprintf("%.1f%%", part/whole*100)
}

func titleCase(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "_", " "), "-", " ")
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	if len(words) == 0 {
		return s
	}
	return strings.Join(words, " ")
}

func truncStr(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "..."
}

func factorUnit(f FactorRef) string {
	if f.Unit == "" {
		return "per unit"
	}
	return "kg/" + f.Unit
}

func orNoun(orgName string) string {
	if strings.TrimSpace(orgName) == "" {
		return "the organization"
	}
	return orgName
}

func shortID(id string) string {
	id = strings.ReplaceAll(id, "-", "")
	if len(id) > 8 {
		return strings.ToUpper(id[:8])
	}
	if id == "" {
		return "ORG"
	}
	return strings.ToUpper(id)
}
