[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd .. && npm ci']

[phases.build]
cmds = ['cd .. && npm run build --workspace web']

[start]
cmd = 'cd .. && npm run start --workspace web'
